version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #           --template-file cfn-template.yml \
  #           --stack-name myInfra-${CIRCLE_WORKFLOW_ID:0:5} \
  #           --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [d5:d1:eb:23:73:ed:f4:01:9a:3f:27:21:64:0a:73:6d]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure Server
          command: |
            ansible-playbook -i inventory main-cfn.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure