version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save-hello-world-output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  
  print-output-file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  my_workflow:
    jobs:
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output